logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

server:
  port: '9081'
  error:
    include-message: always


spring:
  r2dbc:
    password: mySQL@2016
    initialization-mode: always
    url: r2dbc:mysql://localhost:3306/simpleusercloudstreamreactiveserv1
    username: root

  cloud:
    stream:
      function:
        definition: updateUserStatus;summarizeUserRegistrations
      bindings:
        registerUser-out-0:
          destination: user-registration
        updateUserStatus-in-0:
          destination: account-activation
        summarizeUserRegistrations-in-0:
          destination: account-activation

      kafka:
        bindings:
          registerUser-out-0:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.LongSerializer

          updateUserStatus-in-0:
            consumer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.LongSerializer

          summarizeUserRegistrations-in-0:
            consumer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.LongSerializer

        binder:
          brokers: ec2-3-7-157-60.ap-south-1.compute.amazonaws.com:9092

        streams:
          binder:
            configuration:
              application:
                server: ec2-3-7-157-60.ap-south-1.compute.amazonaws.com:9092

            functions:
              updateUserStatus:
                applicationId: updateUserStatus
              summarizeUserRegistrations:
                applicationId: summarizeUserRegistrations

            brokers:
              - ec2-3-7-157-60.ap-south-1.compute.amazonaws.com:9092